dataset:
  name: cldi
  artifacts_dir: artifacts
  train: data/cldi/train.csv
  dev:   data/cldi/dev.csv
  test:  data/cldi/test.csv

columns:
  # CLDI: text = Captions (title) + Hashtags; label = Clickbait
  text_fields: ["Captions", "Hashtags"]
  label: "Clickbait"

# Không có ảnh gốc -> dùng đặc trưng ảnh đã trích sẵn (2048 dims: 0..2047, inclusive)
precomputed:
  enabled: true
  image_range: [0, 2047]   # inclusive

text_encoder:
  enabled: true
  name: "xlm-roberta-large"
  max_length: 128
  batch_size: 16

caption_encoder:
  enabled: false
image_encoder:
  enabled: false
clip:
  enabled: false

runtime:
  device: "auto"
  seed: 42
  cv_folds: 5

models:
  base_learners: ["lr","svm_linear","rf","gbdt","extratrees","mlp"]
  stacking:
    enabled: true
    meta: "logreg"

fusion:
  primary: text
  strategy: concat   # (CLDI không có text_caption)
