dataset:
  name: vcc
  artifacts_dir: artifacts
  train: data/vcc/train.csv
  dev:   data/vcc/dev.csv
  test:  data/vcc/test.csv
  image_root: data/images   # ảnh VCC nằm trong data/images

columns:
  text: "title"
  caption: "caption_vi"
  label: "label"
  claim_image: "thumbnail_url"   # tên file/đường dẫn con dưới image_root

text_encoder:
  enabled: true
  name: "vinai/phobert-large"
  max_length: 128
  batch_size: 16

caption_encoder:
  enabled: true
  name: "vinai/phobert-large"
  max_length: 64
  batch_size: 16

image_encoder:
  enabled: true
  name: "tf_efficientnet_b4"
  root: "data/images"      # (tuỳ chọn, mặc định dùng dataset.image_root)
  image_size: 380

clip:
  enabled: true
  name: "openclip_ViT-B-32"   # hoặc "openai/clip-vit-base-patch32"
  text_enabled: true
  image_enabled: true
  root: "data/images"

precomputed:
  enabled: false

runtime:
  device: "auto"
  seed: 42
  cv_folds: 5

models:
  base_learners: ["lr","svm_linear","rf","gbdt","extratrees","mlp"]
  stacking:
    enabled: true
    meta: "logreg"

fusion:
  primary: text    # text là chủ đạo; caption/image là support
  strategy: concat
